clone_depth: 5

install:
    - set QTDIR=C:\Qt\5.14.2\mingw73_64
    - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
    - md build
    - cd build
    - cmake -G "MinGW Makefiles" ..
    - make
