language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - qtbase5-dev
      - gcc-8

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - VERBOSE=1 make
