language: cpp

dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - qtbase5-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8/"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - VERBOSE=1 make
